version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ENV=production
      - MONGO_DATABASE=task_tracker
      - MONGO_URI=mongodb+srv://utpalkumar74:Utpwd4mongo30%4092@cluster0.ufka7.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0&tls=true&tlsInsecure=true
      - APP_PORT=8080
      - REDIS_ADDRESS=redis-container:6379 # Docker service name used as the Redis hostname
      - ALLOWED_ORIGINS=https://api.trackmytasks.net,https://staging.trackmytasks.net,https://trackmytasks.net,https://www.trackmytasks.net
    depends_on:
      - redis

  redis:
    image: redis:7.0
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: [ "redis-server", "--appendonly", "yes" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

volumes:
  redis_data:
